name: Generative AI

on:
  push:
    paths:
      - 'artificial-intelligence/generative-ai/**'
  pull_request:
    paths:
      - 'artificial-intelligence/generative-ai/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # REF-011-APP-VERSIONING
      - name: Set Build Tag
        run: |
          VERSION=$(grep -oP '__version__\s*=\s*"\K[0-9.]+' artificial-intelligence/generative-ai/backend_for_frontend/__version__.py)
          echo "VERSION=$VERSION"